[package]
name = "dot_proto_parser"
description = "swagger -> .proto files <--> model"
version = "0.0.4"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nom = "7.1.3"    
thiserror = "1.0"  
rand = "0.9.1"
once_cell = "1.18.0" 
either = "1.6" 